### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Scott-Norwood** [CptWesley/NewWorldMinimap#6]
Extracted the full folder to desktop, ran .exe in both normal and elevated, NewWorld running with FPS counter on, 1920x1080 ratio, 70 FoV, graphics on High.

Read: 49611.777, 6215.400, 243,340}
0: Failure
Read: 24£9611.777, 6215.400, 243,340)
1: Failure
Read: if 9611.777, 6215.400, 243,340]
2: <9611.777, 6215.4, 243.34>

Unhandled Exception: System.Runtime.InteropServices.ExternalException: A generic error occurred in GDI+.
   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at NewWorldMinimap.MapImageCache.Get(Int32 x, Int32 y)
   at NewWorldMinimap.MapImageCache.GetTileForCoordinate(Double x, Double y)
   at NewWorldMinimap.MapForm.UpdateLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by CptWesley** [comment]
That's a bit of an odd error. I can't reproduce it. Could you see if it is fixed in the upcoming release?

**Comment by Scott-Norwood** [comment]
Yeah absolutely, I tried to build from your source code and use that one guys merge fix. But that was last night and I saw you accepted his merge, so I was hoping that would of fixed it once you built a release. Cause I couldn't build one from your source but that's because never have built from not my own source.

**Comment by Scott-Norwood** [comment]
Works great now, no errors or anything. Thanks for the hard work!
